Feature/video transport interface
Eyevinn/swift-srt pull request #5
Opened 2021-10-07 13:47 UTC by sinewave440hz

2021-10-11 14:11 UTC, jesperlundqvist approved these changes
Ser bra ut!

2021-10-11 14:11 UTC, jesperlundqvist commented on swift-srt/Stream.swift
> +        self.socket.close()
Kan det bli problem att socketen stängs flera gånger? När jag testade verkade det vara lugnt, men enligt [libsrt](https://github.com/hwangsaeul/libsrt/blob/master/docs/API-functions.md#srt_close) så kan funktionen ge ett error om det är en ogiltig socket. Men det verkar ju inte vara några problem ändå!

2021-10-11 14:15 UTC, sinewave440hz commented on swift-srt/Stream.swift
> +        self.socket.close()
Ja iofs är det nog bra att kolla innan man kör close, vi kan göra så tycker jag 👍

2021-10-11 14:46 UTC, sinewave440hz commented on swift-srt/Stream.swift
> +        self.socket.close()
Har uppdaterat med att spåra uppkopplingen i klassen, men tänker nu att det är ännu bättre att implementera `getStateFromSocket` från wrappern i Socket-klassen. Så jag gör det :)

2021-10-12 14:14 UTC, sinewave440hz commented on swift-srt/Stream.swift
> +        self.socket.close()
Utökat Socket.swift nu med en getState() 👍

2021-10-12 14:29 UTC, jesperlundqvist commented on swift-srt/Socket.swift
> +public enum SRTSocketState: Int {
Kommer värdena från getStateFromSocket översättas rätt?

Det verkar ju vara på [samma sätt i C-apiet](https://github.com/Haivision/srt/blob/ac6ec62a9071b0f7c4410b211a9005792e5d3394/srtcore/srt.h#L168), men behandlar C och Swift dessa lika?

2021-10-13 08:40 UTC, birme requested changes

2021-10-13 08:40 UTC, birme commented on README.md
> +```swift
This seems like a copy-paste error? It looks like the same code as above?

2021-10-13 08:56 UTC, sinewave440hz commented on swift-srt/Socket.swift
> +public enum SRTSocketState: Int {
Ja, det funkade fint vid test, men naturligtvis vore det trevligt att bevisa detta med integrations/enhetstester...

2021-10-13 09:03 UTC, sinewave440hz commented on README.md
> +```swift
Yes... 😊

2021-10-13 09:11 UTC, sinewave440hz commented on swift-srt/Socket.swift
> +public enum SRTSocketState: Int {
#6 Created

2021-10-13 09:12 UTC, merged